# Auto-generated by cargo-makegen

all: build

build:
	cargo build

release:
	cargo build --release

test:
	cargo test

clean:
	cargo clean

run-coordinator:
	cargo run --bin coordinator

run-minidist:
	cargo run --bin minidist

run-minilocal:
	cargo run --bin minilocal

run-netrepl:
	cargo run --bin netrepl

run-worker:
	cargo run --bin worker

# === Makefile.toml tasks ===

dist:
	zip -r Foutzopoulos_Konstantinos_Project.zip src tests docs README.md Cargo.toml
